### ISSUE TITLE
Adverts pages

### ISSUE THREAD

**Issue by bernardbaker** [un7c0rn/stopthevirus#108]
Could you design a page endpoint which is called **advert**. It doesn't need any content.

It will be displayed when the user clicks the verification link in the SMS sent to them as part of **Critical User Journey 1: Starting a game** between (5) and (6).

These pages will be used to generate funds for operational costs.

**Comment by un7c0rn** [comment]
@bernardbaker @dzx11  I think this is a good idea but perhaps leave for post-MVP. Per our discussion let's focus all efforts on getting FE and BE acceptance tests to pass and then subsequently refine.

**Comment by bernardbaker** [comment]
Ok

**Comment by bernardbaker** [comment]
@un7c0rn Used the endpoint mentioned in this issue for the page shown at the end of a user journey. Couldn't think of a name for the end of a user journey page so used this *advert*.
