### ISSUE TITLE
Acceptance tests for front end

### ISSUE THREAD

**Issue by bernardbaker** [un7c0rn/stopthevirus#119]
Using by the [project document](https://docs.google.com/document/d/1ZfS1JQrqZ4bhy63KcxmfJudwLchiIeXaRBpMaa0tNDo/edit#) define acceptance tests that a person can perform.

Documentation, write as though we have a test automation team that are going to follow the steps and run the playbook script.

**Comment by un7c0rn** [comment]
@bernardbaker Just checking in on this. Do we have a FE ATP that I can run through? Helpful not only for testing purposes but for checking out / demo'ing the great UI work you've done.

**Comment by bernardbaker** [comment]
Apologies, but they aren't done yet. I'll send them over to you by close
of business tomorrow 5 PM BST.

Just been caught up with different projects. So couldn't find the time to
get this done properly.

Regards,

Bernard T. A. Baker
