### ISSUE TITLE
Pages needed at the end of a user journey

### ISSUE THREAD

**Issue by bernardbaker** [un7c0rn/stopthevirus#127]
In some instances when a user for instance clicking the SMS link they're redirected to a webhook at which point a page on the app needs open.

Verifying a user or joining a game need a UI page to end the journey.

**Comment by un7c0rn** [comment]
@bernardbaker Agree. Can we reuse and existing page layout design for this and just include a simple success message? Let me know if there are additional requirements.

**Comment by bernardbaker** [comment]
That's what I planned to do.

**Comment by un7c0rn** [comment]
SGTM

**Comment by bernardbaker** [comment]
Done.
