### ISSUE TITLE
Cross browser testing 

### ISSUE THREAD

**Issue by dzx11** [un7c0rn/stopthevirus#129]
@bernardbaker I'll be using this issue to document any issues I find in the front end for this sprint.

**Comment by dzx11** [comment]
🐛 Horizontal scroll bars appear on 1920x1080 resolution at 100% zoom (the rules text at the bottom of the page is too wide)
🐛The join game page throws an error on loading (Unhandled Rejection (Error): error with game info request)
![bug](https://user-images.githubusercontent.com/13459787/81661018-7c426800-9476-11ea-9d10-95443ac83e86.PNG)

**Comment by bernardbaker** [comment]
Great work.

Regarding the error. Are you using a valid game ID?

That is a custom error that should display a custom UI in the event of an
error.

And it shouldn't be shown in production mode.

**Comment by dzx11** [comment]
No, I'm using "12" as an ID. What would be an example valid game ID for this page?

**Comment by bernardbaker** [comment]
I'll get one for you.

**Comment by bernardbaker** [comment]
0H3RzPqfq4dnf47BSgve

**Comment by dzx11** [comment]
That works - I'll add it to the readme

**Comment by bernardbaker** [comment]
The readme shouldn't actually hold an ID it should be a placeholder.

This is because if test haven't been wrong then there may not be an ID
matching in the database.

Put it in if you think it will be helpful.

Regards,
Bernard Baker

**Comment by un7c0rn** [comment]
Closing for now I think the remaining work gets addressed during UAT.
