### ISSUE TITLE
UX: [Start a game page] Design / implement basic page layout using material UI components

### ISSUE THREAD

**Issue by un7c0rn** [un7c0rn/stopthevirus#13]

**Comment by dzx11** [comment]
@un7c0rn @bernardbaker  The doc calls for a Country as well as a phone number input. We can get the country info pretty easily from the phone number, so can we get rid of the country field? I was looking at using this library as an example for the phone number: https://www.npmjs.com/package/material-ui-phone-number

If we have both country and phone fields, we would need to add code to synchronize them because the phone number validation depends on the country.

**Comment by un7c0rn** [comment]
@dzx11 Agreed! Let's drop the country requirement and infer using phone number.

**Comment by bernardbaker** [comment]
I'm not clear on the country being pulled in. Maybe I missed it.

I'll take a look tomorrow morning and let you know.

**Comment by bernardbaker** [comment]
I think the project we are working on was picked in the hackerthon.

⭐⭐⭐⭐⭐

**Comment by un7c0rn** [comment]
@bernardbaker this is for landing / start a game page. Spec lists country as an input requirement so that we can send notifications at reasonable times. David's saying he can infer country using phone number in page implementation.

**Comment by bernardbaker** [comment]
Makes sense now.

**Comment by dzx11** [comment]
@un7c0rn How are we handling TikTok integration? I tried to find an SDK, API or something along those lines like I would use to put in a login button for Facebook, but I didn't find anything. For now I'm leaving the TikTok field as a simple text field.

**Comment by bernardbaker** [comment]
David, I don't think people are signing in with TikTok.

Take a look at the data model and project doc again. Happy to
discuss further.

**Comment by un7c0rn** [comment]
@dzx11 I should update the spec on this, thanks for pointing out! We don't need any TikTok integration on the "Start a game" page. It's just an entry field that requires basic validation and will be stored as metadata. Validating that it's a valid TikTok handle (regex is fine, don't need to query TikTok) should be enough in the short term.

@bernardbaker Has taken care of the TikTok integration on the challenge submission page which parses video metrics given a link.

**Comment by bernardbaker** [comment]
If you need any updates to the TikTok service. Just let me know. Update it
your self, or create an issue for a feature that you need.
