### ISSUE TITLE
UX [Submit challenge entry page]: Design / implement basic page layout using material UI components

### ISSUE THREAD

**Issue by un7c0rn** [un7c0rn/stopthevirus#14]

**Comment by bernardbaker** [comment]
This will be complete when the PR is approved after David reviews it. I'll leave it to you to merge it to develop.

@un7c0rn I think it better practice for you to be the only person who closes issues.

**Comment by un7c0rn** [comment]
@bernardbaker Wow awesome work! I actually did not see this page until I scrolled to the end of the FE README and found this link:

http://localhost:3000/challenge-submission/0044703947287/789632

localhost:3000 is showing attached:

https://ibb.co/nLT8vN9
https://ibb.co/qyWnGzc

And I'm unable to navigate to the challenge-submission page. Am I doing something wrong?

**Comment by bernardbaker** [comment]
No,

That was all the text copy made available to me in previously.

I guess you have to decide what copy you want on the landing page.

I had a few suggestions about navigating and presenting the copy.

**Comment by un7c0rn** [comment]
Right I understand the copy is temporary and we'll update per tasks (17) and (18) but the part I'm a little less clear on is the delta between these screenshots vs. the virus-fe branch which looks like this:

https://ibb.co/Vv4MF9t

And the navigation links work. Please let me know your thoughts on navigating and presenting copy!

**Comment by bernardbaker** [comment]
The landing page work was done before the David did his work.

But it depended on the React spa structure.

So it wasn't pushed.

Those links represent routes which have been created.

But in the wireframes I don't see a screen with all those links.

Re' navigating and presenting copy. I thought an expandable menu could be
used.

Or centered topic text which is swipeable.

There is a lot to convey, with the exception of rules which I needs to be
an indexable web page. And has a button which links to it.

**Comment by un7c0rn** [comment]
@bernardbaker Agree and centered topic text which is swipeable sounds perfect. We don't have official copy yet but it should be relatively brief and fit within a small number of swipeable views.

**Comment by bernardbaker** [comment]
Ok great.

There's a react native swipeable npm library that I've used in the past
which might be useful.

But we want a web version.

**Comment by un7c0rn** [comment]
Marking this as done. I think next steps will require design assets and backend endpoint.

**Comment by bernardbaker** [comment]
Great! Do we have a UI designer?

I know a good one that I've worked with before. I can reach out to her.
