### ISSUE TITLE
API endpoint - batch update tribes

### ISSUE THREAD

**Issue by un7c0rn** [un7c0rn/stopthevirus#19]
Netlify lambda functions are serverless functions which provide an API layer abstraction.

Implement endpoints for each of the functions needed.

@un7c0rn will need to check that the API has all the correct DB writes. Even though there is a project document which provides information.

Tasks completed
- [x] install Firebase
- [x] move configuration values to environment variables
- [x] create Firestore service
- [x] create API endpoint stub
- [x] create test/mock of Firestore service function invoked by API endpoint stub
- [x] create a test with test DB

**Comment by un7c0rn** [comment]
@bernardbaker With the Netlify lambda feature I'm wondering if we still need this. Can we use the Firebase API inside of Netlify lambdas that run server side with pure JS and avoid the need for a GCP endpoint to do the DB writes?

**Comment by bernardbaker** [comment]
@un7c0rn yes that's possible. Will it be as simple as rewriting the python DB implementation in JS?

**Comment by bernardbaker** [comment]
> @un7c0rn yes that's possible. Will it be as simple as rewriting the python DB implementation in JS?

I'm going to copy the python DB implementation with stubs and method signatures.
