### ISSUE TITLE
Create organisation for GitHub collaboration

### ISSUE THREAD

**Issue by bernardbaker** [un7c0rn/stopthevirus#37]
Could you go into your profile settings and create an organisation called "vir-us"?

And invite @bernardbaker and @dzx11.

I should be able to link the development to Netlify after that.

Thanks!

**Comment by un7c0rn** [comment]
Sounds good but will this change our repository URL? Concern here is link breakages with existing references such as the Build for COVID-19 announcement page.

**Comment by bernardbaker** [comment]
@un7c0rn It does break the link.

But it's better that we address it now. Rather than later. When the link will be wide-spread.

We can contact the hackathon organisers, and ask them to update the links. And redistribute them to partners, etc.

**Comment by un7c0rn** [comment]
Closing this for now but we can revisit.
