### ISSUE TITLE
Create a Twilio phone number for each supported country

### ISSUE THREAD

**Issue by un7c0rn** [un7c0rn/stopthevirus#56]
Right now backend Twilio integration supports US. Will need to list our supported countries here, and I can create a Twilio phone number for each. For MVP thinking:

US
UK
Japan

(the countries we're in)

**Comment by bernardbaker** [comment]
I think Italy would be a good idea. They were hit pretty hard by the
pandemic?

I'll look into translations.

Regards,
Bernard

**Comment by un7c0rn** [comment]
@bernardbaker Agree. So support for:

US
UK
JP
IT

**Comment by bernardbaker** [comment]
Hi,

I'll be honest with you both. We're going to need numbers for every country
in the long run.

Regards,
Bernard

**Comment by un7c0rn** [comment]
@bernardbaker I hope so too. Having a finite set will help scope requirements for now to get our E2E tests done.

**Comment by bernardbaker** [comment]
I agree.


Regards,

Bernard T. A. Baker

**Comment by un7c0rn** [comment]
Created U.S. +12568184387

**Comment by un7c0rn** [comment]
Let's leave with U.S. number for now until we get E2E test done.
