### ISSUE TITLE
Implement/overhaul the landing page 

### ISSUE THREAD

**Issue by dzx11** [un7c0rn/stopthevirus#71]
The landing page will be the main point of communication regarding this initiative to help fight COVID19 through social distancing.

It could comprise of:
- A message which will warm the hearts of everyone who reads it.
- Brilliant visual effects.
- A clean and simple UI (which leads to the **start game** page.
- Marketing information
- Media information
- Legal links

**Comment by bernardbaker** [comment]
Just noticed that the animations could be smoother. Created another PR to resolve this.

**Comment by bernardbaker** [comment]
When a user clicks the **get started** button. They navigate to the **start game** page.
