### ISSUE TITLE
Organize front end code in the /components directory

### ISSUE THREAD

**Issue by dzx11** [un7c0rn/stopthevirus#91]
There are too many files in the /components directory. 
Split them using: https://reactjs.org/docs/faq-structure.html
Tests will be in the same folder, and have test.js suffix.

**Comment by bernardbaker** [comment]
@dzx11 thanks. I knew we'd grow in that respect. Do you need this done right now, or can it wait until tomorrow?

**Comment by dzx11** [comment]
@bernardbaker I think best to wait until after current PRs are merged to implement this but we can think of an organizational structure before then.

**Comment by bernardbaker** [comment]
Ok. Would you like to take a call to discuss this?

Or talk via instant messaging?

**Comment by dzx11** [comment]
@bernardbaker Sure, I sent you a message on hangouts

**Comment by bernardbaker** [comment]
@dzx11 let's pair up on this Monday morning GMT if you're available.

**Comment by bernardbaker** [comment]
@dzx11 let's pair up on this Monday morning GMT if you're available.

**Comment by bernardbaker** [comment]
Actually there are other priority tasks.
